# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

# Makes Boost headers available to be used as a C/C++ dependency.

# TODO: Add proper license information citing Drake's license.

HDRS_PATTERNS = [
    "boost/**/*.h",
    "boost/**/*.hpp",
    "boost/**/*.ipp",
]

def _impl(repository_ctx):
    os_name = repository_ctx.os.name
    if os_name == "mac os x":
        prefix = "/opt/homebrew/opt/boost/"
    elif os_name == "linux":
        prefix = "/usr"
    else:
        fail(
            "Operating system is NOT supported",
            attr = repository_ctx.os.name,
        )

    repository_ctx.symlink("{}/include/boost".format(prefix), "boost")

    file_content = """# -*- python -*-

# DO NOT EDIT: generated by boost_repository()

licenses(["notice"])  # BSL-1.0

cc_library(
    name = "boost_headers",
    hdrs = glob({}),
    includes = ["."],
    visibility = ["//visibility:public"],
)
    """.format(HDRS_PATTERNS)

    repository_ctx.file(
        "BUILD.bazel",
        content = file_content,
        executable = False,
    )

boost_repository = repository_rule(
    local = True,
    implementation = _impl,
)
