name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build_linux:
        name: "Build on Linux"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: "Build all targets"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk build --compilation_mode=fastbuild  //...

    build_darwin_arm64:
        name: "Build on macOS (ARM64)"
        runs-on: macos-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: 'Set up latest Oracle JDK 21'
              uses: oracle-actions/setup-java@v1
              with:
                  website: oracle.com
                  release: 21

            - name: "Build all targets"
              run: |
                  tools/bazelisk build --compilation_mode=fastbuild --config=darwin_arm64 //...

    build_darwin_x86:
        name: "Build on macOS (x86)"
        runs-on: macos-13
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: 'Set up latest Oracle JDK 21'
              uses: oracle-actions/setup-java@v1
              with:
                  website: oracle.com
                  release: 21

            - name: "Build all targets"
              run: |
                  tools/bazelisk build --compilation_mode=fastbuild --config=darwin_x86 //...

    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install PyYAML gymnasium loop-rate-limiters msgpack numpy scipy upkie_description

            - name: "Test coverage"
              run: |
                  tools/bazelisk coverage --combined_report=lcov --compilation_mode=fastbuild --instrument_test_targets //...

            - name: "Submit report to Coveralls"
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.github_token }}
                  file: ${{ github.workspace }}/bazel-out/_coverage/_coverage_report.dat
                  format: lcov

    lint:
        name: "Lint code"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install ruff

            - name: "Check code formatting"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test --compilation_mode=fastbuild --config lint //...

            - name: "Check shell scripts formatting"
              run: |
                  find . \
                      -type f \
                      -not \( -path '*/.git/*' -prune \) \
                      -not \( -path '*/wiki/*' -prune \) \
                      -exec sh -c 'head -n 1 {} | grep -q "#!/.*sh"' {} \; \
                      -exec shellcheck {} \;

    test:
        name: "Test on Linux"
        runs-on: ubuntu-latest

        defaults:
            run:
                # See https://github.com/mamba-org/setup-micromamba?tab=readme-ov-file#about-login-shells
                shell: bash -leo pipefail {0}

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Check unit tests"
              env:
                  BAZELISK_GITHUB_TOKEN: ${{ secrets.BAZELISK_GITHUB_TOKEN }}
              run: |
                  tools/bazelisk test --compilation_mode=fastbuild //...

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs:
            - build_darwin_arm64
            - build_darwin_x86
            - build_linux
            - coverage
            - lint
            - test
        steps:
            - run: echo "CI workflow completed successfully"
